/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  titulo: string;
  slug: string;
  /**
   * El header y el footer no van aquí: se editan una sola vez desde Header y Footer en el menú lateral, y aparecen automáticamente en todas las páginas.
   */
  layout?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            backgroundType?: ('image' | 'video') | null;
            image?: (number | null) | Media;
            imageAlt?: string | null;
            imagePosition?: ('left center' | 'center' | 'right center') | null;
            video?: (number | null) | Media;
            primaryButton?: {
              label?: string | null;
              link?: string | null;
              type?: ('fill' | 'outline' | 'underline' | 'arrow' | 'magnetic') | null;
              cursorGrow?: boolean | null;
            };
            secondaryButton?: {
              label?: string | null;
              link?: string | null;
              type?: ('fill' | 'outline' | 'underline' | 'arrow' | 'magnetic') | null;
            };
            isVisible?: boolean | null;
            cursorMarquee?: boolean | null;
            cursorMarqueeText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            viewAllButton?: {
              label?: string | null;
              link?: string | null;
              type?: ('fill' | 'outline' | 'underline' | 'arrow' | 'magnetic') | null;
            };
            projects?:
              | {
                  category?: string | null;
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  imageAlt?: string | null;
                  imagePosition?: ('left center' | 'center' | 'right center' | 'center top') | null;
                  link?: string | null;
                  icon?: ('sprout' | 'users' | 'droplets' | 'heart' | 'leaf' | 'compass') | null;
                  id?: string | null;
                }[]
              | null;
            isVisible?: boolean | null;
            cursorMarquee?: boolean | null;
            backgroundColor?: ('' | 'paper' | 'white' | 'forest' | 'forestDeep' | 'ink') | null;
            cursorMarqueeText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectsSlider';
          }
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            viewAllButton?: {
              label?: string | null;
              link?: string | null;
              type?: ('fill' | 'outline' | 'underline' | 'arrow' | 'magnetic') | null;
            };
            articles?:
              | {
                  category?: string | null;
                  title: string;
                  excerpt?: string | null;
                  image?: (number | null) | Media;
                  imageAlt?: string | null;
                  imagePosition?: ('left center' | 'center' | 'right center') | null;
                  link?: string | null;
                  statistics?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            isVisible?: boolean | null;
            cursorMarquee?: boolean | null;
            backgroundColor?: ('' | 'paper' | 'white' | 'forest' | 'forestDeep' | 'ink') | null;
            cursorMarqueeText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredNews';
          }
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            entranceImage?: (number | null) | Media;
            entranceImageAlt?: string | null;
            viewAllButton?: {
              label?: string | null;
              link?: string | null;
              type?: ('fill' | 'outline' | 'underline' | 'arrow' | 'magnetic') | null;
              cursorGrow?: boolean | null;
            };
            isVisible?: boolean | null;
            cursorMarquee?: boolean | null;
            backgroundColor?: ('' | 'paper' | 'white' | 'forest' | 'forestDeep' | 'ink') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'initiativesSlider';
          }
        | {
            initiatives?:
              | {
                  eyebrow?: string | null;
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  imageAlt?: string | null;
                  link?: string | null;
                  linkLabel?: string | null;
                  type?: ('fill' | 'outline' | 'underline' | 'arrow' | 'magnetic') | null;
                  cursorGrow?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            isVisible?: boolean | null;
            cursorMarquee?: boolean | null;
            backgroundColor?: ('' | 'paper' | 'white' | 'forest' | 'forestDeep' | 'ink') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stickySteps';
          }
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            viewAllButton?: {
              label?: string | null;
              link?: string | null;
            };
            stories?:
              | {
                  title: string;
                  excerpt?: string | null;
                  image?: (number | null) | Media;
                  imageAlt?: string | null;
                  link?: string | null;
                  visualPosition?: ('' | 'large-left' | 'large-right') | null;
                  id?: string | null;
                }[]
              | null;
            isVisible?: boolean | null;
            cursorMarquee?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'storiesEditorial';
          }
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            backgroundImage?: (number | null) | Media;
            viewAllButton?: {
              label?: string | null;
              link?: string | null;
              type?: ('fill' | 'outline' | 'underline' | 'arrow' | 'magnetic') | null;
            };
            opportunities?:
              | {
                  title: string;
                  date?: string | null;
                  location?: string | null;
                  status?: ('open' | 'closed' | 'upcoming') | null;
                  statusLabel?: string | null;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            sliderSettings?: {
              drag?: boolean | null;
              showArrows?: boolean | null;
              showPagination?: boolean | null;
            };
            isVisible?: boolean | null;
            cursorMarquee?: boolean | null;
            backgroundColor?: ('' | 'paper' | 'white' | 'forest' | 'forestDeep' | 'ink') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'opportunitiesSlider';
          }
        | {
            eyebrow?: string | null;
            title: string;
            backgroundType?: ('video' | 'image') | null;
            image?: (number | null) | Media;
            imageAlt?: string | null;
            video?: (number | null) | Media;
            secondTitle?: string | null;
            primaryButton?: {
              label?: string | null;
              link?: string | null;
              type?: ('fill' | 'outline' | 'underline' | 'arrow' | 'magnetic') | null;
              cursorGrow?: boolean | null;
            };
            secondaryLink?: {
              label?: string | null;
              link?: string | null;
              type?: ('fill' | 'outline' | 'underline' | 'arrow' | 'magnetic') | null;
            };
            isVisible?: boolean | null;
            cursorMarquee?: boolean | null;
            backgroundColor?: ('' | 'paper' | 'white' | 'forest' | 'forestDeep' | 'ink') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'scalingMedia';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            viewAllButton?: {
              label?: string | null;
              link?: string | null;
              cursorGrow?: boolean | null;
            };
            contentCardColor?: string | null;
            slides: {
              title: string;
              description: string;
              image: number | Media;
              imageAltOverride?: string | null;
              link?: {
                label?: string | null;
                url?: string | null;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[];
            behavior?: {
              initialSlide?: number | null;
              loop?: boolean | null;
              autoplay?: boolean | null;
              autoplayDelayMs?: number | null;
              enableTouchSwipe?: boolean | null;
              sectionAriaLabel?: string | null;
            };
            isVisible?: boolean | null;
            cursorMarquee?: boolean | null;
            backgroundColor?: ('' | 'paper' | 'white' | 'forest' | 'forestDeep' | 'ink') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitFeatureSlider';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              backgroundType?: T;
              image?: T;
              imageAlt?: T;
              imagePosition?: T;
              video?: T;
              primaryButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                    type?: T;
                    cursorGrow?: T;
                  };
              secondaryButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                    type?: T;
                  };
              isVisible?: T;
              cursorMarquee?: T;
              cursorMarqueeText?: T;
              id?: T;
              blockName?: T;
            };
        projectsSlider?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              viewAllButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                    type?: T;
                  };
              projects?:
                | T
                | {
                    category?: T;
                    title?: T;
                    description?: T;
                    image?: T;
                    imageAlt?: T;
                    imagePosition?: T;
                    link?: T;
                    icon?: T;
                    id?: T;
                  };
              isVisible?: T;
              cursorMarquee?: T;
              backgroundColor?: T;
              cursorMarqueeText?: T;
              id?: T;
              blockName?: T;
            };
        featuredNews?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              viewAllButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                    type?: T;
                  };
              articles?:
                | T
                | {
                    category?: T;
                    title?: T;
                    excerpt?: T;
                    image?: T;
                    imageAlt?: T;
                    imagePosition?: T;
                    link?: T;
                    statistics?:
                      | T
                      | {
                          value?: T;
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              isVisible?: T;
              cursorMarquee?: T;
              backgroundColor?: T;
              cursorMarqueeText?: T;
              id?: T;
              blockName?: T;
            };
        initiativesSlider?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              entranceImage?: T;
              entranceImageAlt?: T;
              viewAllButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                    type?: T;
                    cursorGrow?: T;
                  };
              isVisible?: T;
              cursorMarquee?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        stickySteps?:
          | T
          | {
              initiatives?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    description?: T;
                    image?: T;
                    imageAlt?: T;
                    link?: T;
                    linkLabel?: T;
                    type?: T;
                    cursorGrow?: T;
                    id?: T;
                  };
              isVisible?: T;
              cursorMarquee?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        storiesEditorial?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              viewAllButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                  };
              stories?:
                | T
                | {
                    title?: T;
                    excerpt?: T;
                    image?: T;
                    imageAlt?: T;
                    link?: T;
                    visualPosition?: T;
                    id?: T;
                  };
              isVisible?: T;
              cursorMarquee?: T;
              id?: T;
              blockName?: T;
            };
        opportunitiesSlider?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              backgroundImage?: T;
              viewAllButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                    type?: T;
                  };
              opportunities?:
                | T
                | {
                    title?: T;
                    date?: T;
                    location?: T;
                    status?: T;
                    statusLabel?: T;
                    link?: T;
                    id?: T;
                  };
              sliderSettings?:
                | T
                | {
                    drag?: T;
                    showArrows?: T;
                    showPagination?: T;
                  };
              isVisible?: T;
              cursorMarquee?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        scalingMedia?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              backgroundType?: T;
              image?: T;
              imageAlt?: T;
              video?: T;
              secondTitle?: T;
              primaryButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                    type?: T;
                    cursorGrow?: T;
                  };
              secondaryLink?:
                | T
                | {
                    label?: T;
                    link?: T;
                    type?: T;
                  };
              isVisible?: T;
              cursorMarquee?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        splitFeatureSlider?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              viewAllButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                    cursorGrow?: T;
                  };
              contentCardColor?: T;
              slides?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    imageAltOverride?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              behavior?:
                | T
                | {
                    initialSlide?: T;
                    loop?: T;
                    autoplay?: T;
                    autoplayDelayMs?: T;
                    enableTouchSwipe?: T;
                    sectionAriaLabel?: T;
                  };
              isVisible?: T;
              cursorMarquee?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Este contenido se muestra igual en todas las páginas del sitio. No hace falta repetirlo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navigationItems?:
    | {
        label: string;
        link: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  primaryButton?: {
    label?: string | null;
    link?: string | null;
    type?: ('fill' | 'outline' | 'underline' | 'arrow' | 'magnetic') | null;
    cursorGrow?: boolean | null;
  };
  menuLabel?: string | null;
  hideOnScrollDown?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Este contenido se muestra igual en todas las páginas del sitio. No hace falta repetirlo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  description?: string | null;
  navigationColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              link: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'linkedin' | 'youtube' | 'x';
        link: string;
        iconStyle?: ('fill' | 'outline') | null;
        cursorGrow?: boolean | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navigationItems?:
    | T
    | {
        label?: T;
        link?: T;
        openInNewTab?: T;
        id?: T;
      };
  primaryButton?:
    | T
    | {
        label?: T;
        link?: T;
        type?: T;
        cursorGrow?: T;
      };
  menuLabel?: T;
  hideOnScrollDown?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  description?: T;
  navigationColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        link?: T;
        iconStyle?: T;
        cursorGrow?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}